package report

import (
	"encoding/json"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/happygream/dragnet/internal/model"
)

// WriteJSON saves the report as indented JSON and returns the path.
func WriteJSON(dir string, r model.Report) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	name := fmt.Sprintf("dragnet-%s.json", r.StartedAt.Format("20060102-150405"))
	path := filepath.Join(dir, name)
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// WriteHTML saves a self-contained, styled HTML report and returns the path.
func WriteHTML(dir string, r model.Report) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	name := fmt.Sprintf("dragnet-%s.html", r.StartedAt.Format("20060102-150405"))
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(renderHTML(r)), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func renderHTML(r model.Report) string {
	var b strings.Builder
	b.WriteString(htmlHead)

	b.WriteString(`<div class="wrap">`)
	b.WriteString(`<header><div class="brand">DRAGNET</div><div class="tag">cast the net</div></header>`)

	fmt.Fprintf(&b, `<section class="meta">
<div><span>Target</span><strong>%s</strong></div>
<div><span>Mode</span><strong>%s</strong></div>
<div><span>Hosts up</span><strong>%d</strong></div>
<div><span>Duration</span><strong>%s</strong></div>
<div><span>Started</span><strong>%s</strong></div>
</section>`,
		html.EscapeString(r.Target),
		html.EscapeString(string(r.Mode)),
		r.HostsUp,
		html.EscapeString(r.Duration),
		r.StartedAt.Format(time.RFC1123),
	)

	for _, h := range r.Hosts {
		hostname := h.Hostname
		if hostname == "" {
			hostname = "&mdash;"
		}
		fmt.Fprintf(&b, `<article class="host"><div class="host-head"><h2>%s</h2><span class="hn">%s</span><span class="rtt">%s</span></div>`,
			html.EscapeString(h.IP), hostname, html.EscapeString(h.RTT))

		if h.Honeypot {
			fmt.Fprintf(&b, `<div class="decoy"><span class="decoy-tag">PROBABLE DECOY</span> %s</div>`,
				html.EscapeString(h.HoneypotReason))
		}

		if len(h.OpenPorts) == 0 {
			b.WriteString(`<p class="muted">No open ports found.</p></article>`)
			continue
		}

		b.WriteString(`<table><thead><tr><th>Port</th><th>Service</th><th>Banner</th></tr></thead><tbody>`)
		for _, p := range h.OpenPorts {
			fmt.Fprintf(&b, `<tr><td class="port">%d</td><td>%s</td><td class="banner">%s</td></tr>`,
				p.Port, html.EscapeString(p.Service), html.EscapeString(p.Banner))
		}
		b.WriteString(`</tbody></table>`)

		for _, t := range h.TLS {
			warn := ""
			if len(t.Warnings) > 0 {
				warn = `<div class="warn">` + html.EscapeString(strings.Join(t.Warnings, " • ")) + `</div>`
			}
			fmt.Fprintf(&b, `<div class="card tls"><div class="ct">TLS :%d</div>
<div class="kv"><span>Subject</span>%s</div>
<div class="kv"><span>Issuer</span>%s</div>
<div class="kv"><span>Version</span>%s</div>
<div class="kv"><span>Cipher</span>%s</div>
<div class="kv"><span>Expires in</span>%d days</div>%s</div>`,
				t.Port, html.EscapeString(t.Subject), html.EscapeString(t.Issuer),
				html.EscapeString(t.Version), html.EscapeString(t.CipherSuite),
				t.DaysUntilExpiry, warn)
		}

		for _, ht := range h.HTTP {
			missing := "none"
			if len(ht.MissingHeaders) > 0 {
				missing = html.EscapeString(strings.Join(ht.MissingHeaders, ", "))
			}
			cls := "good"
			if ht.SecurityScore < 50 {
				cls = "bad"
			} else if ht.SecurityScore < 80 {
				cls = "mid"
			}
			fmt.Fprintf(&b, `<div class="card http"><div class="ct">HTTP :%d <span class="score %s">%d/100</span></div>
<div class="kv"><span>Status</span>%d</div>
<div class="kv"><span>Server</span>%s</div>
<div class="kv"><span>Title</span>%s</div>
<div class="kv"><span>Missing</span>%s</div></div>`,
				ht.Port, cls, ht.SecurityScore, ht.StatusCode,
				html.EscapeString(ht.Server), html.EscapeString(ht.Title), missing)
		}

		b.WriteString(`</article>`)
	}

	b.WriteString(`<footer>Generated by dragnet ` + html.EscapeString(r.Version) + `</footer>`)
	b.WriteString(`</div></body></html>`)
	return b.String()
}

const htmlHead = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>dragnet report</title>
<style>
:root{--bg:#0c0a08;--panel:#16120d;--line:#2a2118;--amber:#e8a33d;--amber-dim:#7a5a26;--ink:#e6dccb;--muted:#8a7c66;--bad:#d9534f;--mid:#e8a33d;--good:#6fae5f}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 "JetBrains Mono",ui-monospace,Menlo,Consolas,monospace}
.wrap{max-width:1000px;margin:0 auto;padding:40px 24px}
header{display:flex;align-items:baseline;gap:14px;border-bottom:1px solid var(--line);padding-bottom:18px;margin-bottom:24px}
.brand{font-size:30px;font-weight:700;letter-spacing:.22em;color:var(--amber)}
.tag{color:var(--muted);letter-spacing:.1em;text-transform:uppercase;font-size:11px}
.meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:1px;background:var(--line);border:1px solid var(--line);margin-bottom:28px}
.meta>div{background:var(--panel);padding:12px 14px;display:flex;flex-direction:column;gap:4px}
.meta span{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}
.meta strong{color:var(--amber);font-weight:600}
.host{border:1px solid var(--line);background:var(--panel);margin-bottom:20px;padding:18px}
.host-head{display:flex;align-items:baseline;gap:12px;margin-bottom:14px}
.host-head h2{margin:0;font-size:18px;color:var(--amber);letter-spacing:.04em}
.hn{color:var(--muted)}
.decoy{margin:-4px 0 14px 0;font-size:12px;color:var(--muted);display:flex;align-items:center;gap:10px}
.decoy-tag{background:rgba(217,83,79,.15);color:var(--bad);font-weight:700;letter-spacing:.08em;padding:2px 8px;border:1px solid var(--bad)}
.rtt{margin-left:auto;color:var(--amber-dim);font-size:12px}
table{width:100%;border-collapse:collapse;margin-bottom:14px}
th{text-align:left;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em;border-bottom:1px solid var(--line);padding:6px 8px}
td{padding:6px 8px;border-bottom:1px solid #1d1810}
.port{color:var(--amber);font-weight:600}
.banner{color:var(--muted);font-size:12px}
.card{border:1px solid var(--line);padding:12px 14px;margin:10px 0;background:#120e09}
.ct{color:var(--amber);font-weight:600;margin-bottom:8px;letter-spacing:.04em}
.kv{display:flex;gap:10px;font-size:13px;padding:2px 0}
.kv span{color:var(--muted);min-width:90px}
.warn{margin-top:8px;color:var(--bad);font-size:12px}
.score{font-size:12px;padding:1px 8px;border-radius:2px;margin-left:6px}
.score.good{background:rgba(111,174,95,.15);color:var(--good)}
.score.mid{background:rgba(232,163,61,.15);color:var(--mid)}
.score.bad{background:rgba(217,83,79,.15);color:var(--bad)}
.muted{color:var(--muted)}
footer{margin-top:30px;padding-top:16px;border-top:1px solid var(--line);color:var(--muted);font-size:11px;text-align:center;letter-spacing:.08em}
</style></head><body>`
